services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: finflow_admin_1          # change username if needed
      POSTGRES_PASSWORD: admin@123            # use strong password in prod
      POSTGRES_DB: finflow_db                 # default database to create
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U finflow_admin_1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4-alpine                   # âœ… use latest stable tag
    container_name: finflow-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: [ "redis-server", "--requirepass", "finflow@123" ]
    environment:
      - REDIS_PASSWORD=finflow@123
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "finflow@123", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
