spring:
  application:
    name: discovery-service
server:
  port: ${PORT:4400}
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_HOST_1:http://localhost:4400}/eureka/,${EUREKA_HOST_2:http://localhost:4400}/eureka/
    registry-fetch-interval-seconds: 15
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 60000
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 90


